### ISSUE TITLE
Question About Gustavosta/Stable-Diffusion-Prompts

### ISSUE THREAD

**Issue by whybfq** [YuxinWenRick/diffusion_memorization#4]
1. May I ask the dataset Gustavosta/Stable-Diffusion-Prompts: is it this link [Gustavosta/Stable-Dif](https://huggingface.co/datasets/Gustavosta/Stable-Diffusion-Prompts)?  I used [train.parquet](https://huggingface.co/datasets/Gustavosta/Stable-Diffusion-Prompts/blob/main/data/train.parquet) and convert it to jsonal while it seems incorrct, thanks for your reply. :)
so when I run the code det_mem_viz.ipynb, I met the error:

IndexError                                Traceback (most recent call last)
[<ipython-input-15-dc0b727f8645>](https://localhost:8080/#) in <cell line: 11>()
     21 
     22             curr_data = np.array(row[key])
---> 23             curr_data = curr_data[:num_gens, start:end]
     24             curr_data = np.mean(curr_data, axis=0)
     25 

IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

I think maybe I reproduced the dataset non_memorized_prompts incorrect,

**Comment by whybfq** [comment]
I have run the command

`python3 detect_mem.py --run_name non_memorized_prompts --dataset Gustavosta/Stable-Diffusion-Prompts --end 500 --gen_seed 0` while met error:

Traceback (most recent call last):
  File "/home/Downloads/diffusion_memorization/detect_mem.py", line 100, in <module>
    main(args)
  File "/home/Downloads/diffusion_memorization/detect_mem.py", line 40, in main
    dataset, prompt_key = get_dataset(args.dataset, pipe)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Downloads/diffusion_memorization/optim_utils.py", line 75, in get_dataset
    raise NotImplementedError
NotImplementedError

Thanks a lot for your help.

**Comment by whybfq** [comment]
I  have found the error, thanks.
